language: php
php:
  - 7.2
notifications:
  email: false
services:
  - mysql
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=1"
before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
  - composer run-script lint
  - composer run-script test
